// SQLite expressions the app already uses, rewritten for Postgres.
// Placeholders become $1, $2, … after the date helpers are expanded.

export function translateSql(sql) {
  let text = sql;
  text = text.replace(
    /datetime\(\s*'now'\s*,\s*'([^']*)'\s*\)/gi,
    (_, mod) => `TO_CHAR(CURRENT_TIMESTAMP + INTERVAL '${mod}', 'YYYY-MM-DD HH24:MI:SS')`,
  );
  text = text.replace(
    /date\(\s*'now'\s*,\s*'([^']*)'\s*\)/gi,
    (_, mod) => `(CURRENT_DATE + INTERVAL '${mod}')::text`,
  );
  text = text.replace(
    /datetime\(\s*'now'\s*,\s*\?\s*\)/gi,
    "TO_CHAR(CURRENT_TIMESTAMP + (?::interval), 'YYYY-MM-DD HH24:MI:SS')",
  );
  text = text.replace(
    /datetime\(\s*'now'\s*\)/gi,
    "TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')",
  );
  let index = 0;
  text = text.replace(/\?/g, () => `$${++index}`);
  return text;
}

export function postgresSchema(sql) {
  return translateSql(
    sql.replace(
      /INTEGER PRIMARY KEY/g,
      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ),
  );
}

const IDENTITY_TABLES = [
  "users",
  "contacts",
  "jobs",
  "job_events",
  "measurements",
  "catalogue",
  "proposals",
  "proposal_lines",
  "templates",
  "documents",
  "material_orders",
  "work_orders",
  "invoices",
  "payments",
  "tasks",
  "automations",
];

export function sequenceBumpSql() {
  return IDENTITY_TABLES.map(
    (table) =>
      `SELECT setval(pg_get_serial_sequence('${table}', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM ${table}), 1), 1), true)`,
  ).join(";\n");
}
